server:
  port: 9004
spring:
  datasource:
    url: jdbc:mysql://192.168.25.128:3306/tensquare_article?useUnicode=true&charaterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
  jpa:
    show-sql: true
    generate-ddl: true
    database: mysql