server:
  port: 9001
spring:
  application:
    name: tensquare-base
  datasource:
    url: jdbc:mysql://192.168.25.25:3306/tensquare_base?characterEncoding=UTF-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
  jpa:
    generate-ddl: true
    show-sql: true
    database: mysql
eureka:
  client:
    service-url:
      defaultZone: http://localhost:6868/eureka/
  instance:
    prefer-ip-address: true
