server:
  port: 9001
spring:
  datasource:
    url: jdbc:mysql://192.168.25.128:3306/tensquare_base?characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
  jpa:
    generate-ddl: true
    show-sql: true
    database: mysql
