server:
  port: 12000
spring:
  rabbitmq:
    host: 192.168.25.25
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/lemonman1/springCloudConfig.git
          username: 17688738885
          password: wsmzyz200
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh
