server:
  port: 9009
spring:
  application:
    name: tensquare-friend
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.25.25:3306/tensquare_friend?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
  jpa:
    generate-ddl: true
    show-sql: true
    database: mysql
  redis:
    host: 192.168.25.25
eureka:
  client:
    service-url:
      defaultZone: http://localhost:6868/eureka
  instance:
    prefer-ip-address: true
jwt:
  config:
    key: baidu
    ttl: 360000