server:
  port: 9002
spring:
  application:
    name: tensquare-recruit
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.25.25:3306/tensquare_recruit?useUnicode=true&ampcharacterEncoding=utf-8
    username: root
    password: root

  jpa:
    generate-ddl: true
    show-sql: true
    database: mysql
eureka:
  client:
    service-url:
      defaultZone: http://localhost:6868/eureka
  instance:
    prefer-ip-address: true