server:
  port: 9004
spring:
  application:
    name: tensquare-article
  datasource:
    url: jdbc:mysql://192.168.25.25:3306/tensquare_article?useUnicode=true&charaterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
  jpa:
    show-sql: true
    generate-ddl: true
    database: mysql
  data:
    mongodb:
      host: 192.168.25.25
      database:  recruitdb
eureka:
  client:
    service-url:
      defaultZone: http://localhost:6868/eureka
  instance:
    prefer-ip-address: true