server:
  port: 9005
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.25.25:3306/tensquare_gathering?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
  jpa:
    generate-ddl: true
    database: mysql
    show-sql: true
  redis:
    url: 192.168.25.25
